url: http://ibmstreams.github.io/tutorials/
baseurl: /tutorials
github_editme_path: IBMStreams/tutorials/blob/gh-pages

# Site settings
title: IBM Streams Tutorials
description: "IBM Streams Tutorials"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
detach:  false
port:    4000
host:    127.0.0.1
